meteor:
  image: ulexus/meteor:legacy
  environment:
    ROOT_URL: https://justgrimes.review
    MONGO_URL: mongodb://db:27017/justgrimes-review
    RELEASE: 1.3.5.1
  links:
    - db
  volumes:
    - .:/src/app
  restart: always
db:
  image: mongo:3.0.2
  volumes:
    - /srv/db:/data/db
  restart: always
proxy:
  image: annixa/docker-nginx-letsencrypt-proxy
  environment:
    PROXY_DEST: http://meteor/
    LE_DOMAIN: justgrimes.review
    LE_EMAIL: info@justgrimes.review
    SLACK_NOTIFICATIONS_INFRA_URL: "${SLACK_WEBHOOK_URL}"
  ports:
    - "80:80"
    - "443:443"
  links:
    - meteor
  volumes:
    - /srv/certs:/certs
  restart: always
