version: '2'

services:
  meteor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROOT_URL=https://justgrimes.review
      - MONGO_URL=mongodb://db:27017/justgrimes-review
      - PORT=3000
      - VIRTUAL_HOST=justgrimes.review,justgrimes.horse
      - LETSENCRYPT_HOST=justgrimes.review,justgrimes.horse
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true
    links:
      - db
    volumes:
      - .:/src/app
    restart: always
  db:
    image: mongo:3.6
    volumes:
      - /srv/db:/data/db
    restart: always
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=info@justgrimes.review
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
